column_width = 200
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "Always"
# Never, FunctionOnly, ConditionalOnly, or Always
# collapse_simple_statement = "Always"