name: Lint

on:
  pull_request:
    branches:
      - "main"

jobs:
  lua:
    name: Lint Lua files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: |
          make formatlua
          git diff --exit-code

      - name: Lint
        run: make checklua

  queries:
    name: Format query files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: |
          make formatquery
          git diff --exit-code

  readme:
    name: Lint docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check SUPPORTED_LANGUAGES
        run: |
          make docs
          git diff --exit-code
